#이미지 빌드시 이름을 ECR 쪽으로 변경
app = docker.build("public.ecr.aws/r3n7f5t8/test")

# ECR에서 생성한 Repository URI로 변경 및 Jenkins AWS Credential으로 변경
docker.withRegistry('https://public.ecr.aws/r3n7f5t8', 'ecr:ap-northeast-2:test-ecr-credentials')

# Full Code
  
node {
     stage('Clone repository') {
         checkout scm
     }

     stage('Build image') {
         app = docker.build("public.ecr.aws/r3n7f5t8/test")
     }

     stage('Push image') {
         sh 'rm  ~/.dockercfg || true'
         sh 'rm ~/.docker/config.json || true'
         
         docker.withRegistry('https://public.ecr.aws/r3n7f5t8/test', 'ecr:ap-northeast-2:test-ecr-credentials') {
             app.push("${env.BUILD_NUMBER}")
             app.push("latest")
     }
  }
}
